# Generated by Django 5.0.6 on 2024-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('email_sau_telefon', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
            ],
        ),
    ]
