# Generated by Django 5.0.6 on 2024-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformatiiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.CharField(max_length=255)),
                ('numar_telefon', models.CharField(max_length=15)),
                ('metoda_plata', models.CharField(max_length=15)),
                ('cos_cumparaturi', models.CharField(max_length=1000)),
            ],
        ),
    ]
