# Generated by Django 5.0.6 on 2024-10-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informatiiclient',
            name='metoda_plata',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('online_payment', 'Online Payment')], max_length=20),
        ),
    ]
