# Generated by Django 5.0.6 on 2024-10-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_informatiiclient_metoda_plata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informatiiclient',
            old_name='metoda_plata',
            new_name='payment_method',
        ),
    ]
