# Generated by Django 5.0.6 on 2024-10-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mancare', '0001_initial'),
        ('cart', '0003_rename_metoda_plata_informatiiclient_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informatiiclient',
            name='cos_cumparaturi',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.informatiiclient')),
                ('produse', models.ManyToManyField(to='Mancare.reteta')),
            ],
        ),
    ]
